# Generated by Django 4.2.26 on 2025-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('success', 'success'), ('fail', 'fail')], default='pending', max_length=20),
        ),
    ]
