# Generated by Django 4.2.26 on 2025-11-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_orderrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], default='PENDING', max_length=20),
        ),
    ]
