# Generated by Django 4.2.26 on 2025-11-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_order_delete_orderrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderRequest',
        ),
        migrations.AlterModelTable(
            name='orderrequest',
            table='order_request',
        ),
    ]
