# Generated by Django 4.2.26 on 2025-11-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_rename_order_orderrequest_alter_orderrequest_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='gap',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='price',
        ),
    ]
