# Generated by Django 4.2.26 on 2025-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_remove_orderrequest_gap_remove_orderrequest_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='created_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='gap',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('매매전', '매매전'), ('매수중', '매수중'), ('매도중', '매도중'), ('완료', '완료'), ('실패', '실패')], default='매매전', max_length=20),
        ),
    ]
