# Generated by Django 4.2.26 on 2025-11-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_rename_created_at_orderrequest_requested_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='gap',
            new_name='target_profit',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='buy_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='kis_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='kis_order_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='sell_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTING', 'REQUESTING'), ('REQUEST_FAILED', 'REQUEST_FAILED'), ('BUYING', 'BUYING'), ('SELLING', 'SELLING'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10)),
                ('executed_price', models.IntegerField(null=True)),
                ('executed_qty', models.IntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.orderrequest')),
            ],
            options={
                'db_table': 'order_execution',
            },
        ),
    ]
