# Generated by Django 4.2.26 on 2025-12-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_rename_gap_orderrequest_target_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexecution',
            name='executed_at',
            field=models.DateTimeField(),
        ),
    ]
