# Generated by Django 4.2.26 on 2025-12-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_orderexecution_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderexecution',
            name='executed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderexecution',
            name='executed_qty',
            field=models.IntegerField(null=True),
        ),
    ]
