# Generated by Django 4.2.26 on 2025-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_orderexecution_executed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='sell_target_price',
            field=models.IntegerField(null=True),
        ),
    ]
