# Generated by Django 4.2.26 on 2025-12-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_orderrequest_sell_target_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='sell_target_price',
            new_name='target_price',
        ),
    ]
