# Generated by Django 4.2.26 on 2025-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_rename_sell_target_price_orderrequest_target_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='buy_requested_at',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='sell_requested_at',
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTING', 'REQUESTING'), ('REQUEST_FAILED', 'REQUEST_FAILED'), ('BUYING', 'BUYING'), ('BUY_PENDING', 'BUY_PENDING'), ('BUY_DONE', 'BUY_DONE'), ('SELL_PENDING', 'SELL_PENDING'), ('SELL_REQUEST_FAILED', 'SELL_REQUEST_FAILED'), ('SELL_DONE', 'SELL_DONE')], default='PENDING', max_length=20),
        ),
    ]
