# Generated by Django 4.2.26 on 2025-12-01 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_remove_orderrequest_buy_requested_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderrequest',
            name='kis_message',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='kis_order_id',
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='kis_message',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='kis_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
