# Generated by Django 4.2.26 on 2025-12-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_remove_orderrequest_kis_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexecution',
            old_name='executed_qty',
            new_name='executed_quantity',
        ),
        migrations.RenameField(
            model_name='orderexecution',
            old_name='side',
            new_name='executed_type',
        ),
    ]
