# Generated by Django 4.2.26 on 2025-12-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_rename_executed_qty_orderexecution_executed_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderexecution',
            old_name='executed_type',
            new_name='executed_side',
        ),
    ]
