# Generated by Django 4.2.26 on 2025-12-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_rename_executed_type_orderexecution_executed_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REQUESTING', 'REQUESTING'), ('REQUEST_FAILED', 'REQUEST_FAILED'), ('BUYING', 'BUYING'), ('BUY_REQUEST_FAILEDBUY_PENDING', 'BUY_REQUEST_FAILEDBUY_PENDING'), ('BUY_DONE', 'BUY_DONE'), ('SELL_PENDING', 'SELL_PENDING'), ('SELL_REQUEST_FAILED', 'SELL_REQUEST_FAILED'), ('SELL_DONE', 'SELL_DONE')], default='BUY_PENDING', max_length=50),
        ),
    ]
